import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "../../globals.css"; // Import your global styles if needed

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div></div>
        {/* <div className="m-5"></div> */}
        {children}
        <footer></footer>
      </body>
    </html>
  );
}
